version: '3.7'

services:
  nginx:
    image: motion8/nginx:1.16-dev
    ports:
      - 80:80
    environment:
      # proxy_pass to...
      APP_PORT: 8000
      APP_DNS: app
    depends_on:
      - app

  app:
    build: ./src
    command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
      - ./data/:/data2import/
    environment:
      DATABASE_URL: postgresql://fuelsaveio:fuelsaveio@db/fuelsaveio
      SECRET_KEY: "897902aef01ba9689fa8d1a7c3e9b287a55fdc288d07d742a73f3c5173d03330"
      PASSWORD_SALT: "3c56bce732f31ff1485d015f51bf05afe5623c87d0cff86d79ead3b0f7631f4c"
      ALGORITHM: "HS256"
      TOKEN_TTL_MINUTES: 10
      DATA_IMPORT_PATH: "/data2import"
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=fuelsaveio
      # TODO hide secret
      - POSTGRES_PASSWORD=fuelsaveio
      - POSTGRES_DB=fuelsaveio

  zookeeper:
    image: 'bitnami/zookeeper:3'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
