version: '3.7'

services:
  nginx:
    image: motion8/nginx:1.16-dev
    ports:
      - 80:80
    environment:
      # proxy_pass to...
      APP_PORT: 8080
      APP_DNS: app
    depends_on:
      - app

  app:
    image: fastapi-bp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Gunicorn
      PORT: 8080
    ports:
      - 8080:8080